version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: afpa-chatbot-rag:latest
    container_name: afpa-chatbot-rag
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge 